language: python

python:
  - "3.3"
  - "3.2"

install:
  - pip install . --quiet
  - pip install git+https://github.com/kennethreitz/requests
  - pip install pytest nose --quiet

script: nosetests

branches:
  only:
    - master
